# Generated by Django 4.2.27 on 2026-01-09 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=4, default=0.5, max_digits=5)),
                ('pool_balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.outcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'outcome')},
            },
        ),
    ]
