# Generated by Django 4.2.27 on 2026-01-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_outcome_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='winning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_markets', to='markets.outcome'),
        ),
    ]
