# Generated by Django 4.2.27 on 2026-01-09 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0003_market_winning_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_markets', to=settings.AUTH_USER_MODEL),
        ),
    ]
